name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Configure AWS credentials
        run: |
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials

      - name: Build and deploy to AWS Beanstalk
        run: |
          npm ci
          npm run build
          zip -r application.zip .
          aws s3 cp application.zip s3://YOUR_S3_BUCKET/application.zip
          aws elasticbeanstalk create-application-version --application-name YOUR_APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=YOUR_S3_BUCKET,S3Key=application.zip
          aws elasticbeanstalk update-environment --application-name YOUR_APPLICATION_NAME --environment-name YOUR_ENVIRONMENT_NAME --version-label $GITHUB_SHA
